# Generated by Django 4.0.1 on 2022-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateogory',
            new_name='category',
        ),
    ]
