# Generated by Django 4.0.1 on 2022-01-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ser',
            new_name='user',
        ),
    ]
